baseURL: "https://www.syslog.my.id/"
title: "Viki Pranata"
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: Viki Pranata
  description: "This is my journal"
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  images: "assets/images/profile.jpg"
  DateFormat: "February 2, 1997"
  defaultTheme: light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  analytics:
      google:
          SiteVerificationTag: G-FWN6N1CDFZ

  assets:
    favicon: "assets/images/panda.png"
    favicon16x16: "assets/images/panda.png"
    favicon32x32: "assets/images/panda.png"
    apple_touch_icon: "assets/images/panda.png"
    safari_pinned_tab: "assets/images/panda.png"

  label:
    text: "Home"
    icon: assets/images/panda.png
    iconHeight: 20

  profileMode:
      enabled: true
      title: "Viki Pranata"
      subtitle: "Positive life start from positive mind."
      imageUrl: "assets/images/profile.jpg"
      imageTitle: "me"
      imageWidth: 200
      imageHeight: 200
      buttons:
          - name: Blogs
            url: https://blog.syslog.my.id
          - name: Badges
            url: "https://www.credly.com/users/vikipranata"

  socialIcons:
    - name: email
      url: "mailto:helovikipranata@gmail.com"
    - name: telegram
      url: "https://t.me/vikipranata"
    - name: instagram
      url: "https://instagram.com/vikipranata"
    - name: twitter
      url: "https://twitter.com/vikipranata"
    - name: github
      url: "https://github.com/vikipranata"
    - name: linkedin
      url: "https://www.linkedin.com/in/vikipranata"
  
  editPost:
  URL: "https://github.com/vikipranata/vikipranata.github.io/blob/main/content"
  Text: "Suggest Changes"
  appendFilePath: true

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

menu:
  main:
    - identifier: About
      name: About
      url: /about/
      weight: 10
    - identifier: Posts
      name: Posts
      url: https://blog.syslog.my.id
      weight: 20

pygmentsUseClasses: true
markup:
  highlight:
    # noClasses: false
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai
